language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - "lts/*"
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

branches:
  only:
    - chapter-ui-tests

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

install:
    - npm ci

script:
  - npm run ci
  - npx ngh --dir=dist/ngws --repo=https://$GITHUB_TOKEN@github.com/digitaldrummerj/angular-tutorial-code.git

# deploy:
#   provider: pages
#   skip_cleanup: true # To avoid cleanup of the artifact generated during script
#   github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
#   local_dir: dist/ngws # Replace this with your project name
#   on:
#     branch: chapter-ui-tests
